# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def pods
#  pod 'RxSwift'
  pod 'Moya/RxSwift'
end

#MARK: - VideoDB_CleanArchitecture Target

target 'VideoDB_CleanArchitecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoDB_CleanArchitecture
  pods
  pod 'Kingfisher'
  pod 'RxCocoa'
  pod 'RxDataSources'

end

#MARK: - Domain Target

target 'Domain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Domain
  pods
  
end

#MARK: - NetworkPlatform Target

target 'NetworkPlatform' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkPlatform
  pods
  
end

#MARK: - CoredataPlatform Target

target 'CoredataPlatform' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoredataPlatform
  pod 'RxCoreData'
  pod 'RxDataSources'

end
