# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def pods
#  pod 'RxSwift'
  pod 'Moya/RxSwift'
end

target 'VideoDB_CleanArchitecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoDB_CleanArchitecture
  pods
  pod 'Kingfisher'
  pod 'RxCocoa'
  pod 'RxDataSources'

end


target 'Domain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Domain
  pods
  
end

target 'NetworkPlatform' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Domain
  pods
  
end

